import { AngkaItem } from '../types';

export const ANGKA_DATA: AngkaItem[] = [
  {
    angka: 1,
    terbilang: 'Satu',
    objekNama: 'Matahari Bersinar',
    emoji: '☀️',
    warna: '#F59E0B',
    bgGradasi: 'from-amber-400 to-yellow-500',
    listObjek: ['☀️'],
  },
  {
    angka: 2,
    terbilang: 'Dua',
    objekNama: 'Apel Manis',
    emoji: '🍎',
    warna: '#EF4444',
    bgGradasi: 'from-red-400 to-rose-500',
    listObjek: ['🍎', '🍎'],
  },
  {
    angka: 3,
    terbilang: 'Tiga',
    objekNama: 'Bintang Terang',
    emoji: '⭐',
    warna: '#EAB308',
    bgGradasi: 'from-yellow-400 to-amber-500',
    listObjek: ['⭐', '⭐', '⭐'],
  },
  {
    angka: 4,
    terbilang: 'Empat',
    objekNama: 'Kupu-kupu Cantik',
    emoji: '🦋',
    warna: '#8B5CF6',
    bgGradasi: 'from-purple-400 to-indigo-500',
    listObjek: ['🦋', '🦋', '🦋', '🦋'],
  },
  {
    angka: 5,
    terbilang: 'Lima',
    objekNama: 'Balon Warna-warni',
    emoji: '🎈',
    warna: '#EC4899',
    bgGradasi: 'from-pink-400 to-rose-500',
    listObjek: ['🎈', '🎈', '🎈', '🎈', '🎈'],
  },
  {
    angka: 6,
    terbilang: 'Enam',
    objekNama: 'Bunga Mekar',
    emoji: '🌸',
    warna: '#10B981',
    bgGradasi: 'from-emerald-400 to-teal-500',
    listObjek: ['🌸', '🌸', '🌸', '🌸', '🌸', '🌸'],
  },
  {
    angka: 7,
    terbilang: 'Tujuh',
    objekNama: 'Jeruk Segar',
    emoji: '🍊',
    warna: '#F97316',
    bgGradasi: 'from-orange-400 to-amber-500',
    listObjek: ['🍊', '🍊', '🍊', '🍊', '🍊', '🍊', '🍊'],
  },
  {
    angka: 8,
    terbilang: 'Delapan',
    objekNama: 'Stroberi Merah',
    emoji: '🍓',
    warna: '#EF4444',
    bgGradasi: 'from-rose-400 to-red-500',
    listObjek: ['🍓', '🍓', '🍓', '🍓', '🍓', '🍓', '🍓', '🍓'],
  },
  {
    angka: 9,
    terbilang: 'Sembilan',
    objekNama: 'Permen Manis',
    emoji: '🍬',
    warna: '#06B6D4',
    bgGradasi: 'from-cyan-400 to-blue-500',
    listObjek: ['🍬', '🍬', '🍬', '🍬', '🍬', '🍬', '🍬', '🍬', '🍬'],
  },
  {
    angka: 10,
    terbilang: 'Sepuluh',
    objekNama: 'Hati Ceria',
    emoji: '💖',
    warna: '#3B82F6',
    bgGradasi: 'from-blue-400 to-indigo-600',
    listObjek: ['💖', '💖', '💖', '💖', '💖', '💖', '💖', '💖', '💖', '💖'],
  },
];
