import { HewanItem } from '../types';

export const HEWAN_DATA: HewanItem[] = [
  {
    id: 'kucing',
    nama: 'Kucing',
    emoji: '🐱',
    suaraTeks: 'Meong.. meong..',
    suaraKarakter: 'Kucing suka bermain dan dielus lembut.',
    suaraAudioType: 'kucing',
    habitat: 'Rumah & Taman',
    warna: '#F59E0B',
    makanan: 'Ikan segar',
  },
  {
    id: 'anjing',
    nama: 'Anjing',
    emoji: '🐶',
    suaraTeks: 'Guk.. guk..',
    suaraKarakter: 'Anjing sahabat setia yang suka bermain bola.',
    suaraAudioType: 'anjing',
    habitat: 'Rumah',
    warna: '#3B82F6',
    makanan: 'Biskuit',
  },
  {
    id: 'ayam',
    nama: 'Ayam',
    emoji: '🐔',
    suaraTeks: 'Kukuruyuk!',
    suaraKarakter: 'Ayam berkokok riang menyambut pagi hari.',
    suaraAudioType: 'ayam',
    habitat: 'Peternakan',
    warna: '#EF4444',
    makanan: 'Biji jagung',
  },
  {
    id: 'sapi',
    nama: 'Sapi',
    emoji: '🐮',
    suaraTeks: 'Mooo..',
    suaraKarakter: 'Sapi menghasilkan susu segar yang sehat dan bergizi.',
    suaraAudioType: 'sapi',
    habitat: 'Padang rumput',
    warna: '#10B981',
    makanan: 'Rumput hijau',
  },
  {
    id: 'kambing',
    nama: 'Kambing',
    emoji: '🐐',
    suaraTeks: 'Mbeeek..',
    suaraKarakter: 'Kambing lincah suka melompat-lompat gembira.',
    suaraAudioType: 'kambing',
    habitat: 'Bukit & Padang rumput',
    warna: '#8B5CF6',
    makanan: 'Dedaunan segar',
  },
  {
    id: 'ikan',
    nama: 'Ikan',
    emoji: '🐠',
    suaraTeks: 'Kecipak-kecipuk..',
    suaraKarakter: 'Ikan berenang gesit dan bebas di dalam air bersih.',
    suaraAudioType: 'ikan',
    habitat: 'Laut & Sungai',
    warna: '#06B6D4',
    makanan: 'Makanan ikan kecil',
  },
  {
    id: 'burung',
    nama: 'Burung',
    emoji: '🐦',
    suaraTeks: 'Cit.. cit.. cuit!',
    suaraKarakter: 'Burung bernyanyi merdu dan terbang tinggi di langit.',
    suaraAudioType: 'burung',
    habitat: 'Pohon & Alam bebas',
    warna: '#EC4899',
    makanan: 'Biji-bijian',
  },
  {
    id: 'gajah',
    nama: 'Gajah',
    emoji: '🐘',
    suaraTeks: 'Teeeet..!',
    suaraKarakter: 'Gajah bertubuh besar dengan telinga lebar dan belalai kuat.',
    suaraAudioType: 'gajah',
    habitat: 'Hutan tropis',
    warna: '#6366F1',
    makanan: 'Tumbuhan & Buah-buahan',
  },
];
