import { HurufItem } from '../types';

export const HURUF_DATA: HurufItem[] = [
  {
    huruf: 'A',
    kata: 'Apel',
    artinya: 'Buah apel manis dan merah',
    emoji: '🍎',
    warna: '#EF4444',
    bgGradasi: 'from-red-400 to-rose-500',
    kalimat: 'A untuk Apel. Apel rasanya manis dan segar!',
  },
  {
    huruf: 'B',
    kata: 'Bola',
    artinya: 'Bola untuk bermain bersama teman',
    emoji: '⚽',
    warna: '#3B82F6',
    bgGradasi: 'from-blue-400 to-indigo-500',
    kalimat: 'B untuk Bola. Ayo kita bermain bola!',
  },
  {
    huruf: 'C',
    kata: 'Ceri',
    artinya: 'Buah ceri kecil yang lezat',
    emoji: '🍒',
    warna: '#EC4899',
    bgGradasi: 'from-pink-400 to-rose-500',
    kalimat: 'C untuk Ceri. Ceri warnanya merah cerah!',
  },
  {
    huruf: 'D',
    kata: 'Domba',
    artinya: 'Domba lucu berbulu putih lembut',
    emoji: '🐑',
    warna: '#10B981',
    bgGradasi: 'from-emerald-400 to-teal-500',
    kalimat: 'D untuk Domba. Mbek, suara domba yang lucu!',
  },
  {
    huruf: 'E',
    kata: 'Elang',
    artinya: 'Burung elang terbang tinggi di langit',
    emoji: '🦅',
    warna: '#F59E0B',
    bgGradasi: 'from-amber-400 to-orange-500',
    kalimat: 'E untuk Elang. Elang punya sayap yang kuat!',
  },
  {
    huruf: 'F',
    kata: 'Foto',
    artinya: 'Kamera untuk foto tersenyum',
    emoji: '📷',
    warna: '#8B5CF6',
    bgGradasi: 'from-purple-400 to-indigo-500',
    kalimat: 'F untuk Foto. Cekrek, tersenyum manis!',
  },
  {
    huruf: 'G',
    kata: 'Gajah',
    artinya: 'Gajah besar dengan belalai panjang',
    emoji: '🐘',
    warna: '#6366F1',
    bgGradasi: 'from-indigo-400 to-sky-500',
    kalimat: 'G untuk Gajah. Gajah badannya sangat besar!',
  },
  {
    huruf: 'H',
    kata: 'Harimau',
    artinya: 'Harimau loreng yang gagah',
    emoji: '🐯',
    warna: '#F97316',
    bgGradasi: 'from-orange-400 to-amber-500',
    kalimat: 'H untuk Harimau. Harimau berlari sangat cepat!',
  },
  {
    huruf: 'I',
    kata: 'Ikan',
    artinya: 'Ikan berenang riang di air',
    emoji: '🐟',
    warna: '#06B6D4',
    bgGradasi: 'from-cyan-400 to-blue-500',
    kalimat: 'I untuk Ikan. Ikan berenang di laut luas!',
  },
  {
    huruf: 'J',
    kata: 'Jerapah',
    artinya: 'Jerapah punya leher yang sangat tinggi',
    emoji: '🦒',
    warna: '#EAB308',
    bgGradasi: 'from-yellow-400 to-amber-500',
    kalimat: 'J untuk Jerapah. Jerapah suka makan daun pohon!',
  },
  {
    huruf: 'K',
    kata: 'Kucing',
    artinya: 'Kucing manis mengeong lembut',
    emoji: '🐱',
    warna: '#14B8A6',
    bgGradasi: 'from-teal-400 to-emerald-500',
    kalimat: 'K untuk Kucing. Meong meong, kucing lucu sekali!',
  },
  {
    huruf: 'L',
    kata: 'Lebah',
    artinya: 'Lebah rajin membuat madu manis',
    emoji: '🐝',
    warna: '#F59E0B',
    bgGradasi: 'from-amber-400 to-yellow-500',
    kalimat: 'L untuk Lebah. Nguung, lebah menghasilkan madu lezat!',
  },
  {
    huruf: 'M',
    kata: 'Mobil',
    artinya: 'Mobil beroda empat untuk jalan-jalan',
    emoji: '🚗',
    warna: '#EF4444',
    bgGradasi: 'from-red-400 to-pink-500',
    kalimat: 'M untuk Mobil. Brum brum, mobil melaju kencang!',
  },
  {
    huruf: 'N',
    kata: 'Nanas',
    artinya: 'Buah nanas segar bersisik mahkota',
    emoji: '🍍',
    warna: '#EAB308',
    bgGradasi: 'from-yellow-400 to-orange-500',
    kalimat: 'N untuk Nanas. Nanas buah tropis yang lezat!',
  },
  {
    huruf: 'O',
    kata: 'Orangutan',
    artinya: 'Orangutan pintar di hutan rindang',
    emoji: '🦧',
    warna: '#D97706',
    bgGradasi: 'from-amber-500 to-yellow-600',
    kalimat: 'O untuk Orangutan. Orangutan suka bergelantungan di pohon!',
  },
  {
    huruf: 'P',
    kata: 'Pisang',
    artinya: 'Buah pisang kuning bergizi tinggi',
    emoji: '🍌',
    warna: '#FACC15',
    bgGradasi: 'from-yellow-300 to-amber-400',
    kalimat: 'P untuk Pisang. Nyam nyam, pisang enak sekali!',
  },
  {
    huruf: 'Q',
    kata: 'Quran',
    artinya: 'Kitab suci dibaca dengan hati suci',
    emoji: '📖',
    warna: '#10B981',
    bgGradasi: 'from-emerald-400 to-green-600',
    kalimat: 'Q untuk Quran. Mari membaca dengan tekun dan santun!',
  },
  {
    huruf: 'R',
    kata: 'Rumah',
    artinya: 'Rumah hangat tempat berkumpul keluarga',
    emoji: '🏡',
    warna: '#3B82F6',
    bgGradasi: 'from-blue-400 to-sky-500',
    kalimat: 'R untuk Rumah. Rumahku nyaman dan penuh cinta!',
  },
  {
    huruf: 'S',
    kata: 'Sepeda',
    artinya: 'Sepeda seru untuk bersepeda ceria',
    emoji: '🚲',
    warna: '#8B5CF6',
    bgGradasi: 'from-purple-400 to-pink-500',
    kalimat: 'S untuk Sepeda. Kring kring gowes sepeda sore hari!',
  },
  {
    huruf: 'T',
    kata: 'Topi',
    artinya: 'Topi keren melindungi dari matahari',
    emoji: '🧢',
    warna: '#06B6D4',
    bgGradasi: 'from-cyan-400 to-blue-500',
    kalimat: 'T untuk Topi. Pakai topi saat cuaca cerah!',
  },
  {
    huruf: 'U',
    kata: 'Udang',
    artinya: 'Udang lincah di dalam perairan',
    emoji: '🦐',
    warna: '#F97316',
    bgGradasi: 'from-orange-400 to-rose-500',
    kalimat: 'U untuk Udang. Udang makanan sehat kaya nutrisi!',
  },
  {
    huruf: 'V',
    kata: 'Vas',
    artinya: 'Vas bunga cantik penghias meja',
    emoji: '🏺',
    warna: '#A855F7',
    bgGradasi: 'from-purple-400 to-violet-600',
    kalimat: 'V untuk Vas. Di dalam vas ada bunga yang mekar harum!',
  },
  {
    huruf: 'W',
    kata: 'Wortel',
    artinya: 'Wortel oranye bagus untuk mata',
    emoji: '🥕',
    warna: '#EA580C',
    bgGradasi: 'from-orange-500 to-amber-500',
    kalimat: 'W untuk Wortel. Kelinci sangat suka makan wortel!',
  },
  {
    huruf: 'X',
    kata: 'Xilofon',
    artinya: 'Alat musik berdenting riang',
    emoji: '🎵',
    warna: '#EC4899',
    bgGradasi: 'from-pink-400 to-purple-500',
    kalimat: 'X untuk Xilofon. Ting ting ting, suaranya sangat merdu!',
  },
  {
    huruf: 'Y',
    kata: 'Yoyo',
    artinya: 'Mainan yoyo naik dan turun seru',
    emoji: '🪀',
    warna: '#10B981',
    bgGradasi: 'from-emerald-400 to-teal-500',
    kalimat: 'Y untuk Yoyo. Lempar ke bawah dan tarik kembali ke atas!',
  },
  {
    huruf: 'Z',
    kata: 'Zebra',
    artinya: 'Zebra bergaris hitam dan putih',
    emoji: '🦓',
    warna: '#64748B',
    bgGradasi: 'from-slate-400 to-gray-600',
    kalimat: 'Z untuk Zebra. Zebra punya corak garis yang sangat unik!',
  },
];
