import { QuizQuestion } from '../types';

export const KUIS_QUESTIONS: QuizQuestion[] = [
  {
    id: 1,
    kategori: 'WARNA',
    pertanyaan: 'Mana yang merupakan warna Merah?',
    suaraTeks: 'Mana yang merupakan warna merah?',
    pilihan: [
      { id: 'a', label: 'Biru', visual: '🔵', isColor: true, colorHex: '#3B82F6' },
      { id: 'b', label: 'Merah', visual: '🔴', isColor: true, colorHex: '#EF4444' },
      { id: 'c', label: 'Kuning', visual: '🟡', isColor: true, colorHex: '#EAB308' },
      { id: 'd', label: 'Hijau', visual: '🟢', isColor: true, colorHex: '#10B981' },
    ],
    jawabanBenarId: 'b',
    pujian: 'Hebat! Itu adalah warna Merah cerah!',
  },
  {
    id: 2,
    kategori: 'HEWAN',
    pertanyaan: 'Hewan mana yang bersuara "Meong... meong"?',
    suaraTeks: 'Hewan mana yang bersuara meong meong?',
    pilihan: [
      { id: 'a', label: 'Kucing', visual: '🐱' },
      { id: 'b', label: 'Sapi', visual: '🐮' },
      { id: 'c', label: 'Ayam', visual: '🐔' },
      { id: 'd', label: 'Ikan', visual: '🐟' },
    ],
    jawabanBenarId: 'a',
    pujian: 'Pintar sekali! Kucing bersuara meong meong!',
  },
  {
    id: 3,
    kategori: 'ANGKA',
    pertanyaan: 'Hitung bintang ini: ⭐ ⭐ ⭐. Ada berapa?',
    suaraTeks: 'Hitung bintang ini, ada berapa?',
    pilihan: [
      { id: 'a', label: '2', subLabel: 'Dua', visual: '2️⃣' },
      { id: 'b', label: '3', subLabel: 'Tiga', visual: '3️⃣' },
      { id: 'c', label: '4', subLabel: 'Empat', visual: '4️⃣' },
    ],
    jawabanBenarId: 'b',
    pujian: 'Luar biasa! Benar ada 3 bintang bersinar!',
  },
  {
    id: 4,
    kategori: 'HURUF',
    pertanyaan: 'Huruf awal untuk kata "Apel" 🍎 adalah?',
    suaraTeks: 'Huruf awal untuk kata Apel adalah?',
    pilihan: [
      { id: 'a', label: 'B', visual: '🅱️' },
      { id: 'b', label: 'C', visual: '🔤' },
      { id: 'c', label: 'A', visual: '🅰️' },
    ],
    jawabanBenarId: 'c',
    pujian: 'Hebat! A untuk Apel yang manis!',
  },
  {
    id: 5,
    kategori: 'WARNA',
    pertanyaan: 'Mana warna Kuning seperti matahari? ☀️',
    suaraTeks: 'Mana yang merupakan warna kuning seperti matahari?',
    pilihan: [
      { id: 'a', label: 'Kuning', visual: '🟡', isColor: true, colorHex: '#EAB308' },
      { id: 'b', label: 'Ungu', visual: '🟣', isColor: true, colorHex: '#A855F7' },
      { id: 'c', label: 'Hitam', visual: '⚫', isColor: true, colorHex: '#1E293B' },
      { id: 'd', label: 'Biru', visual: '🔵', isColor: true, colorHex: '#3B82F6' },
    ],
    jawabanBenarId: 'a',
    pujian: 'Wah hebat! Kuning hangat seperti mentari!',
  },
  {
    id: 6,
    kategori: 'HEWAN',
    pertanyaan: 'Hewan mana yang memiliki belalai panjang?',
    suaraTeks: 'Hewan mana yang memiliki belalai panjang?',
    pilihan: [
      { id: 'a', label: 'Gajah', visual: '🐘' },
      { id: 'b', label: 'Burung', visual: '🐦' },
      { id: 'c', label: 'Kambing', visual: '🐐' },
      { id: 'd', label: 'Anjing', visual: '🐶' },
    ],
    jawabanBenarId: 'a',
    pujian: 'Keren! Gajah punya belalai yang panjang dan kuat!',
  },
  {
    id: 7,
    kategori: 'ANGKA',
    pertanyaan: 'Mana angka 5 (Lima)?',
    suaraTeks: 'Mana angka lima?',
    pilihan: [
      { id: 'a', label: '3', visual: '3️⃣' },
      { id: 'b', label: '5', visual: '5️⃣' },
      { id: 'c', label: '7', visual: '7️⃣' },
      { id: 'd', label: '9', visual: '9️⃣' },
    ],
    jawabanBenarId: 'b',
    pujian: 'Benar sekali! Itu adalah angka 5 (lima)!',
  },
  {
    id: 8,
    kategori: 'WARNA',
    pertanyaan: 'Warna apakah daun pohon pada umumnya? 🍃',
    suaraTeks: 'Warna apakah daun pohon pada umumnya?',
    pilihan: [
      { id: 'a', label: 'Merah', visual: '🔴', isColor: true, colorHex: '#EF4444' },
      { id: 'b', label: 'Hijau', visual: '🟢', isColor: true, colorHex: '#10B981' },
      { id: 'c', label: 'Ungu', visual: '🟣', isColor: true, colorHex: '#A855F7' },
      { id: 'd', label: 'Hitam', visual: '⚫', isColor: true, colorHex: '#1E293B' },
    ],
    jawabanBenarId: 'b',
    pujian: 'Pintar! Daun segar berwarna Hijau sejuk!',
  },
  {
    id: 9,
    kategori: 'HEWAN',
    pertanyaan: 'Hewan mana yang berkokok "Kukuruyuk" di pagi hari?',
    suaraTeks: 'Hewan mana yang berkokok kukuruyuk di pagi hari?',
    pilihan: [
      { id: 'a', label: 'Ayam', visual: '🐔' },
      { id: 'b', label: 'Kucing', visual: '🐱' },
      { id: 'c', label: 'Bebek', visual: '🦆' },
      { id: 'd', label: 'Anjing', visual: '🐶' },
    ],
    jawabanBenarId: 'a',
    pujian: 'Tepat sekali! Ayam jantan berkokok kukuruyuk!',
  },
  {
    id: 10,
    kategori: 'HURUF',
    pertanyaan: 'Huruf apa setelah huruf B?',
    suaraTeks: 'Huruf apa setelah huruf B?',
    pilihan: [
      { id: 'a', label: 'A', visual: '🅰️' },
      { id: 'b', label: 'C', visual: '🔤' },
      { id: 'c', label: 'D', visual: '🔤' },
    ],
    jawabanBenarId: 'b',
    pujian: 'Hebat! A, B, lalu huruf C!',
  },
  {
    id: 11,
    kategori: 'ANGKA',
    pertanyaan: 'Berapa banyak balon ini? 🎈 🎈',
    suaraTeks: 'Berapa banyak balon ini? Satu, dua...',
    pilihan: [
      { id: 'a', label: '1 (Satu)', visual: '1️⃣' },
      { id: 'b', label: '2 (Dua)', visual: '2️⃣' },
      { id: 'c', label: '4 (Empat)', visual: '4️⃣' },
    ],
    jawabanBenarId: 'b',
    pujian: 'Pintar! Ada dua balon melayang riang!',
  },
  {
    id: 12,
    kategori: 'HEWAN',
    pertanyaan: 'Hewan apa yang berenang lincah di dalam air?',
    suaraTeks: 'Hewan apa yang berenang lincah di dalam air?',
    pilihan: [
      { id: 'a', label: 'Ikan', visual: '🐠' },
      { id: 'b', label: 'Gajah', visual: '🐘' },
      { id: 'c', label: 'Kambing', visual: '🐐' },
      { id: 'd', label: 'Ayam', visual: '🐔' },
    ],
    jawabanBenarId: 'a',
    pujian: 'Hebat sekali! Ikan lincah berenang di air!',
  },
  {
    id: 13,
    kategori: 'HURUF',
    pertanyaan: 'Huruf awal untuk kata "Bola" ⚽ adalah?',
    suaraTeks: 'Huruf awal untuk kata Bola adalah?',
    pilihan: [
      { id: 'a', label: 'A', visual: '🅰️' },
      { id: 'b', label: 'B', visual: '🅱️' },
      { id: 'c', label: 'C', visual: '🔤' },
    ],
    jawabanBenarId: 'b',
    pujian: 'Keren! B untuk Bola sepak!',
  },
  {
    id: 14,
    kategori: 'WARNA',
    pertanyaan: 'Warna apakah langit yang cerah di siang hari? 🌤️',
    suaraTeks: 'Warna apakah langit yang cerah di siang hari?',
    pilihan: [
      { id: 'a', label: 'Biru', visual: '🔵', isColor: true, colorHex: '#3B82F6' },
      { id: 'b', label: 'Merah', visual: '🔴', isColor: true, colorHex: '#EF4444' },
      { id: 'c', label: 'Hitam', visual: '⚫', isColor: true, colorHex: '#1E293B' },
      { id: 'd', label: 'Ungu', visual: '🟣', isColor: true, colorHex: '#A855F7' },
    ],
    jawabanBenarId: 'a',
    pujian: 'Betul! Langit yang indah berwarna Biru!',
  },
  {
    id: 15,
    kategori: 'HEWAN',
    pertanyaan: 'Hewan mana yang bersuara "Mooo" dan memberi kita susu? 🥛',
    suaraTeks: 'Hewan mana yang bersuara Mooo dan memberi susu?',
    pilihan: [
      { id: 'a', label: 'Sapi', visual: '🐮' },
      { id: 'b', label: 'Anjing', visual: '🐶' },
      { id: 'c', label: 'Burung', visual: '🐦' },
      { id: 'd', label: 'Ikan', visual: '🐠' },
    ],
    jawabanBenarId: 'a',
    pujian: 'Hebat! Sapi lucu bersuara Mooo!',
  },
  {
    id: 16,
    kategori: 'ANGKA',
    pertanyaan: 'Hitung permen ini: 🍬 🍬 🍬 🍬 🍬. Ada berapa?',
    suaraTeks: 'Hitung permen ini, ada berapa permen?',
    pilihan: [
      { id: 'a', label: '3 (Tiga)', visual: '3️⃣' },
      { id: 'b', label: '4 (Empat)', visual: '4️⃣' },
      { id: 'c', label: '5 (Lima)', visual: '5️⃣' },
      { id: 'd', label: '6 (Enam)', visual: '6️⃣' },
    ],
    jawabanBenarId: 'c',
    pujian: 'Tepat sekali! Ada 5 permen manis!',
  },
  {
    id: 17,
    kategori: 'WARNA',
    pertanyaan: 'Mana yang merupakan warna Putih seperti awan? ☁️',
    suaraTeks: 'Mana warna putih seperti awan?',
    pilihan: [
      { id: 'a', label: 'Putih', visual: '⚪', isColor: true, colorHex: '#F8FAFC' },
      { id: 'b', label: 'Hitam', visual: '⚫', isColor: true, colorHex: '#1E293B' },
      { id: 'c', label: 'Merah', visual: '🔴', isColor: true, colorHex: '#EF4444' },
      { id: 'd', label: 'Kuning', visual: '🟡', isColor: true, colorHex: '#EAB308' },
    ],
    jawabanBenarId: 'a',
    pujian: 'Pintar! Awan lembut berwarna Putih!',
  },
  {
    id: 18,
    kategori: 'HEWAN',
    pertanyaan: 'Hewan mana yang punya sayap dan berkicau merdu? 🎶',
    suaraTeks: 'Hewan mana yang punya sayap dan berkicau merdu?',
    pilihan: [
      { id: 'a', label: 'Burung', visual: '🐦' },
      { id: 'b', label: 'Gajah', visual: '🐘' },
      { id: 'c', label: 'Sapi', visual: '🐮' },
      { id: 'd', label: 'Kambing', visual: '🐐' },
    ],
    jawabanBenarId: 'a',
    pujian: 'Benar sekali! Burung bernyanyi cit cit cuit!',
  },
  {
    id: 19,
    kategori: 'ANGKA',
    pertanyaan: 'Berapa jumlah matahari di tata surya kita? ☀️',
    suaraTeks: 'Berapa jumlah matahari di langit kita?',
    pilihan: [
      { id: 'a', label: '1 (Satu)', visual: '1️⃣' },
      { id: 'b', label: '2 (Dua)', visual: '2️⃣' },
      { id: 'c', label: '3 (Tiga)', visual: '3️⃣' },
    ],
    jawabanBenarId: 'a',
    pujian: 'Pintar! Ada satu matahari yang menyinari bumi!',
  },
  {
    id: 20,
    kategori: 'HEWAN',
    pertanyaan: 'Hewan mana yang bersuara "Mbeeek... mbeeek"?',
    suaraTeks: 'Hewan mana yang bersuara Mbeek mbeek?',
    pilihan: [
      { id: 'a', label: 'Kambing', visual: '🐐' },
      { id: 'b', label: 'Kucing', visual: '🐱' },
      { id: 'c', label: 'Ayam', visual: '🐔' },
      { id: 'd', label: 'Anjing', visual: '🐶' },
    ],
    jawabanBenarId: 'a',
    pujian: 'Hebat! Kambing melompat sambil bersuara mbeeek!',
  },
];
