import { WarnaItem } from '../types';

export const WARNA_DATA: WarnaItem[] = [
  {
    id: 'merah',
    nama: 'Merah',
    hex: '#EF4444',
    bgTailwind: 'bg-red-500',
    textTailwind: 'text-red-500',
    deskripsi: 'Warna merah cerah dan penuh semangat!',
    contohBenda: [
      { nama: 'Apel', emoji: '🍎' },
      { nama: 'Stroberi', emoji: '🍓' },
      { nama: 'Mobil Pemadam', emoji: '🚒' },
      { nama: 'Hati', emoji: '❤️' },
    ],
  },
  {
    id: 'kuning',
    nama: 'Kuning',
    hex: '#EAB308',
    bgTailwind: 'bg-yellow-400',
    textTailwind: 'text-yellow-500',
    deskripsi: 'Warna kuning hangat dan ceria seperti mentari!',
    contohBenda: [
      { nama: 'Matahari', emoji: '☀️' },
      { nama: 'Pisang', emoji: '🍌' },
      { nama: 'Bintang', emoji: '⭐' },
      { nama: 'Bebek Kuning', emoji: '🐥' },
    ],
  },
  {
    id: 'biru',
    nama: 'Biru',
    hex: '#3B82F6',
    bgTailwind: 'bg-blue-500',
    textTailwind: 'text-blue-500',
    deskripsi: 'Warna biru tenang seperti langit cerah dan laut!',
    contohBenda: [
      { nama: 'Langit', emoji: '🌤️' },
      { nama: 'Laut', emoji: '🌊' },
      { nama: 'Ikan Paus', emoji: '🐳' },
      { nama: 'Balon Biru', emoji: '🎈' },
    ],
  },
  {
    id: 'hijau',
    nama: 'Hijau',
    hex: '#10B981',
    bgTailwind: 'bg-emerald-500',
    textTailwind: 'text-emerald-500',
    deskripsi: 'Warna hijau sejuk seperti dedaunan di alam!',
    contohBenda: [
      { nama: 'Daun', emoji: '🍃' },
      { nama: 'Semangka', emoji: '🍉' },
      { nama: 'Pohon', emoji: '🌳' },
      { nama: 'Katak', emoji: '🐸' },
    ],
  },
  {
    id: 'ungu',
    nama: 'Ungu',
    hex: '#A855F7',
    bgTailwind: 'bg-purple-500',
    textTailwind: 'text-purple-500',
    deskripsi: 'Warna ungu manis seperti buah anggur!',
    contohBenda: [
      { nama: 'Anggur', emoji: '🍇' },
      { nama: 'Terong', emoji: '🍆' },
      { nama: 'Bunga Cantik', emoji: '🪻' },
      { nama: 'Pita Ungu', emoji: '🎀' },
    ],
  },
  {
    id: 'oranye',
    nama: 'Oranye',
    hex: '#F97316',
    bgTailwind: 'bg-orange-500',
    textTailwind: 'text-orange-500',
    deskripsi: 'Warna oranye segar seperti buah jeruk manis!',
    contohBenda: [
      { nama: 'Jeruk', emoji: '🍊' },
      { nama: 'Wortel', emoji: '🥕' },
      { nama: 'Labu', emoji: '🎃' },
      { nama: 'Singa', emoji: '🦁' },
    ],
  },
  {
    id: 'hitam',
    nama: 'Hitam',
    hex: '#1E293B',
    bgTailwind: 'bg-slate-800',
    textTailwind: 'text-slate-800',
    deskripsi: 'Warna hitam kuat dan pekat seperti malam!',
    contohBenda: [
      { nama: 'Malam Gelap', emoji: '🌙' },
      { nama: 'Kucing Hitam', emoji: '🐈‍⬛' },
      { nama: 'Ban Mobil', emoji: '🛞' },
      { nama: 'Semut', emoji: '🐜' },
    ],
  },
  {
    id: 'putih',
    nama: 'Putih',
    hex: '#F8FAFC',
    bgTailwind: 'bg-slate-100',
    textTailwind: 'text-slate-600',
    deskripsi: 'Warna putih bersih dan lembut seperti awan!',
    contohBenda: [
      { nama: 'Awan', emoji: '☁️' },
      { nama: 'Susu Segar', emoji: '🥛' },
      { nama: 'Kelinci', emoji: '🐇' },
      { nama: 'Telur', emoji: '🥚' },
    ],
  },
];
